version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:80"
    container_name: "testcontainer"
    volumes:
      - ./:/app
    entrypoint: /start-reload.sh
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: airport
    ports:
      - "3308:3306"
    container_name: "openflightsdb"
