version: "3.8"
volumes:
  db_info:
services:
  app:
    build: .
    ports:
      - "80:80"
    container_name: "appcontainer"
    depends_on:
      - db
    entrypoint: /start-reload.sh
  db:
    image: mysql
    restart: always
    volumes:
      - db_info:/var/lib/mysql
      - ./app/data:/data
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLROOTPASS}
      MYSQL_DATABASE: openflights
      MYSQL_USER: ${SQLUSER}
      MYSQL_PASSWORD: ${SQLPASS}
    ports:
      - "3308:3306"
    container_name: "openflightsdb"
    command: --secure-file-priv=''
