version: "3.8"
services:
  app:
    build:
      context: .
      target: test
    ports:
      - "80:80"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "pytest"]
  db:
    image: mysql
    restart: always
    volumes:
      - ./app/data:/data
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLROOTPASS}
      MYSQL_DATABASE: openflights
      MYSQL_USER: ${SQLUSER}
      MYSQL_PASSWORD: ${SQLPASS}
    ports:
      - "3308:3306"
    command: --secure-file-priv=''
